baseurl: "/jekyll-blog"
title: "Example blog"
description: "An example blog that uses jekyll-blog-theme"
icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Blogger_icon_2017.svg/1200px-Blogger_icon_2017.svg.png"